/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematcc;

import javax.swing.JButton;

/**
 *
 * @author rob
 */
public class PanelWhoAmI extends javax.swing.JPanel {

    /**
     * Creates new form PanelWhoAmI
     */
    public PanelWhoAmI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudProfessores = new javax.swing.JButton();
        souProfessor = new javax.swing.JButton();
        souAluno1 = new javax.swing.JButton();
        crudAlunos = new javax.swing.JButton();

        crudProfessores.setText("CRUD Professores");
        crudProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudProfessoresActionPerformed(evt);
            }
        });

        souProfessor.setText("Sou Professor da Disciplina");
        souProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                souProfessorActionPerformed(evt);
            }
        });

        souAluno1.setText("Sou Aluno");
        souAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                souAluno1ActionPerformed(evt);
            }
        });

        crudAlunos.setText("CRUD Alunos");
        crudAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudAlunosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(souAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(souProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(crudProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(crudAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(souAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(souProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(crudProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(293, Short.MAX_VALUE)
                    .addComponent(crudAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crudProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudProfessoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crudProfessoresActionPerformed

    private void souProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_souProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_souProfessorActionPerformed

    private void souAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_souAluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_souAluno1ActionPerformed

    private void crudAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crudAlunosActionPerformed

    public JButton getSouAluno() {
        return souProfessor;
    }

    public JButton getSouProfessor() {
        return souProfessor;
    }

    public JButton getCrudAlunos() {
        return crudAlunos;
    }

    public JButton getCrudProfessores() {
        return crudProfessores;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crudAlunos;
    private javax.swing.JButton crudProfessores;
    private javax.swing.JButton souAluno1;
    private javax.swing.JButton souProfessor;
    // End of variables declaration//GEN-END:variables
}
